module.exports = {
  SIZE: 300,
  FRAMES: 24,
  SPRITE_NAMES: ["ALIEN", "BEAR", "CAT", "DOG", "DUCK", "FROG", "MOOSE", "PINEAPPLE", "ROBOT", "SHARK", "UNICORN"],
  MOVE_NAMES: [
    {name: "Rest", mirror: true, rest: true},
    {name: "ClapHigh", mirror: true},
    {name: "Clown", mirror: false, burstReversed: true},
    {name: "Dab", mirror: true},
    {name: "DoubleJam", mirror: false, burstReversed: true},
    {name: "Drop", mirror: true},
    {name: "Floss", mirror: true, burstReversed: true},
    {name: "Fresh", mirror: true},
    {name: "Kick", mirror: true, burstReversed: true},
    {name: "Roll", mirror: true, burstReversed: true},
    {name: "ThisOrThat", mirror: false, burstReversed: true},
    {name: "Thriller", mirror: true, burstReversed: true},
    {name: "XArmsSide", mirror: false, shortBurst: true},
    {name: "XArmsUp", mirror: false, shortBurst: true},
    {name: "XJump", mirror: false, shortBurst: true},
    {name: "XClapSide", mirror: false, shortBurst: true},
    {name: "XHeadHips", mirror: false, shortBurst: true, burstReversed: true},
    {name: "XHighKick", mirror: false, shortBurst: true},
    {name: "XBend", mirror: false, shortBurst: true},
    {name: "XFever", mirror: false, shortBurst: true},
    {name: "XHop", mirror: false, shortBurst: true},
    {name: "XKnee", mirror: false, shortBurst: true},
    {name: "XKneel", mirror: false, shortBurst: true},
    {name: "XOle", mirror: false, shortBurst: true},
    {name: "XSlide", mirror: false, shortBurst: true},
  ],
};
